/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicSpinBoxRouteImport } from './routes/api/public/spin-box'
import { Route as ApiPublicRedeemVoucherRouteImport } from './routes/api/public/redeem-voucher'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpinBoxRoute = ApiPublicSpinBoxRouteImport.update({
  id: '/api/public/spin-box',
  path: '/api/public/spin-box',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedeemVoucherRoute = ApiPublicRedeemVoucherRouteImport.update({
  id: '/api/public/redeem-voucher',
  path: '/api/public/redeem-voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/admin/login': typeof AdminLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/redeem-voucher': typeof ApiPublicRedeemVoucherRoute
  '/api/public/spin-box': typeof ApiPublicSpinBoxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/admin/login': typeof AdminLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/redeem-voucher': typeof ApiPublicRedeemVoucherRoute
  '/api/public/spin-box': typeof ApiPublicSpinBoxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/admin/login': typeof AdminLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/redeem-voucher': typeof ApiPublicRedeemVoucherRoute
  '/api/public/spin-box': typeof ApiPublicSpinBoxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/orders'
    | '/search'
    | '/admin/login'
    | '/category/$slug'
    | '/product/$id'
    | '/admin/'
    | '/api/public/checkout'
    | '/api/public/redeem-voucher'
    | '/api/public/spin-box'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/orders'
    | '/search'
    | '/admin/login'
    | '/category/$slug'
    | '/product/$id'
    | '/admin'
    | '/api/public/checkout'
    | '/api/public/redeem-voucher'
    | '/api/public/spin-box'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/orders'
    | '/search'
    | '/admin/login'
    | '/category/$slug'
    | '/product/$id'
    | '/admin/'
    | '/api/public/checkout'
    | '/api/public/redeem-voucher'
    | '/api/public/spin-box'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  OrdersRoute: typeof OrdersRoute
  SearchRoute: typeof SearchRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicRedeemVoucherRoute: typeof ApiPublicRedeemVoucherRoute
  ApiPublicSpinBoxRoute: typeof ApiPublicSpinBoxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spin-box': {
      id: '/api/public/spin-box'
      path: '/api/public/spin-box'
      fullPath: '/api/public/spin-box'
      preLoaderRoute: typeof ApiPublicSpinBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/redeem-voucher': {
      id: '/api/public/redeem-voucher'
      path: '/api/public/redeem-voucher'
      fullPath: '/api/public/redeem-voucher'
      preLoaderRoute: typeof ApiPublicRedeemVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  OrdersRoute: OrdersRoute,
  SearchRoute: SearchRoute,
  AdminLoginRoute: AdminLoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicRedeemVoucherRoute: ApiPublicRedeemVoucherRoute,
  ApiPublicSpinBoxRoute: ApiPublicSpinBoxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
